name: Google Trends Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # 每個小時的第 0 分鐘執行

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the trend tracker script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          G_SHEET_ID: ${{ secrets.G_SHEET_ID }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_SENDER_APP_PASSWORD: ${{ secrets.EMAIL_SENDER_APP_PASSWORD }}
        run: python trend_tracker.py
